name: Auto Add Issues to Project

on:
  issues:
    types: [opened, labeled, edited]
  workflow_call:

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    #- name: Set up GitHub CLI
   #   uses: cli/cli@v2
    #  with:
     #   version: latest

    - name: Add issue to project if labeled
      if: |
        contains(github.event.issue.labels.*.name, 'metap')
      run: |
        echo "Adding issue #${{ github.event.issue.number }} to the project board"
        
        # GitHub REST API URL for adding an issue to a project
        ISSUE_NUMBER="${{ github.event.issue.number }}"
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        
        curl -X POST \
          --url https://api.github.com/graphql \
          -H "Authorization: Bearer $TOKEN" \
          -d '{"query":"mutation {addProjectV2ItemById(input: {projectId: \"179\" contentId: \"$ISSUE_NUMBER\"}) {item {id}}}"}'
